export { default as arrow } from './icons/arrow';
export { default as pinCircle } from './icons/pinCircle';
export {
  default as arrowDoubleSidedCurved,
} from './icons/arrowDoubleSidedCurved';
export {
  default as arrowDoubleSidedDiagonal,
} from './icons/arrowDoubleSidedDiagonal';
export { default as visaCard } from './icons/visaCard';
export { default as unionPayCard } from './icons/unionPayCard';
export { default as masterCard } from './icons/masterCard';
export { default as dinersClubCard } from './icons/dinersClubCard';
export { default as jCBCard } from './icons/jCBCard';
export { default as momoCard } from './icons/momoCard';
export { default as discoverCard } from './icons/discoverCard';
export { default as aMEXCard } from './icons/aMEXCard';
export { default as settingsSliders } from './icons/settingsSliders';
export { default as microphone } from './icons/microphone';
export { default as percentage } from './icons/percentage';
export { default as crossedParcelBox } from './icons/crossedParcelBox';
export { default as tickedParcelBox } from './icons/tickedParcelBox';
export { default as networkParcelBox } from './icons/networkParcelBox';
export { default as magnify } from './icons/magnify';
export { default as send } from './icons/send';
export { default as calendar } from './icons/calendar';
export { default as parcelBoxOutline } from './icons/parcelBoxOutline';
export { default as sendPaperPlane } from './icons/sendPaperPlane';
export { default as download } from './icons/download';
export { default as refresh } from './icons/refresh';
export { default as save } from './icons/saveIcon';
export { default as editSymbol } from './icons/editSymbol';
export { default as privacyIcon1 } from './icons/privacyIcon1';
export { default as privacyIcon2 } from './icons/privacyIcon2';
export { default as facebookColored } from './icons/facebookColored';
export { default as googlePlusColored } from './icons/googlePlusColored';
export { default as phoneIcon1 } from './icons/phoneIcon1';
export { default as textMessage2 } from './icons/textMessage2';
export { default as magnifyingGlass } from './icons/magnifyingGlass';
export { default as key } from './icons/key';
export { default as pin2 } from './icons/pin2';
export { default as aMEXLogo } from './icons/aMEXLogo';
export { default as visaLogo } from './icons/visaLogo';
export { default as masterCardLogo } from './icons/masterCardLogo';
export { default as androidLogo } from './icons/androidLogo';
export { default as heartSymbol } from './icons/heartSymbol';
export { default as addContact } from './icons/addContact';
export { default as directions } from './icons/directions';
export { default as sound } from './icons/sound';
export { default as spanner } from './icons/spanner';
export { default as bangkokBank } from './icons/bangkokBank';
export { default as blockedGroup } from './icons/blockedGroup';
